# Generated by Django 3.2.25 on 2024-06-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sticky_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stickynote',
            old_name='created_at',
            new_name='published_date',
        ),
    ]
