# Generated by Django 3.2.25 on 2024-06-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sticky_app', '0003_alter_stickynote_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stickynote',
            old_name='color',
            new_name='colour',
        ),
    ]
