# Generated by Django 3.2.25 on 2024-06-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sticky_app', '0004_rename_color_stickynote_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickynote',
            name='colour',
        ),
    ]
